<?php

namespace SantosSabanari\LaravelFoundation\Console\Commands;

use Illuminate\Console\GeneratorCommand;
use Illuminate\Filesystem\Filesystem;
use Illuminate\Support\Str;

class DeleteTableCommand extends GeneratorCommand
{
    protected $signature = 'laravel-foundation:delete-table
                            {name : The name of the table}';

    protected $description = 'Delete a table generated by package';

    protected $type = 'Remove Table';

    public function handle()
    {
        $name = $this->argument('name');
        $firstword = Str::title(str_replace('-',' ',$name));
        $studly = Str::studly($name);
        $camel = Str::camel($name);

        $this->info('Remove Table ' . $firstword);

        (new Filesystem())->delete(app_path("Services/$studly"."Service.php"));
        (new Filesystem())->delete(app_path("Models/$studly.php"));
        (new Filesystem())->delete(app_path("Events/$studly"."Created.php"));
        (new Filesystem())->delete(app_path("Events/$studly"."Deleted.php"));
        (new Filesystem())->delete(app_path("Events/$studly"."Updated.php"));
        (new Filesystem())->delete(app_path("Traits/$studly"."Attribute.php"));
        (new Filesystem())->delete(app_path("Traits/$studly"."Method.php"));
        (new Filesystem())->delete(app_path("Traits/$studly"."Scope.php"));
        (new Filesystem())->delete(app_path("Listeners/$studly"."EventListener.php"));
        (new Filesystem())->delete(database_path("factories/$studly"."Factory.php"));
        (new Filesystem())->delete(database_path("seeders/$studly"."Seeder.php"));

        $this->comment('Please remove manually:');
        $this->comment('1. Migration');

        $this->info('Remove Table ' . $name . ' done!');
    }

    protected function getStub()
    {
        return '';
    }
}
