<?php

namespace SantosSabanari\LaravelFoundation\Console\Commands;

use Illuminate\Console\GeneratorCommand;
use Illuminate\Filesystem\Filesystem;
use Illuminate\Support\Str;

class DeleteReportCommand extends GeneratorCommand
{
    protected $signature = 'laravel-foundation:delete-report
                            {name : The name of the report}';

    protected $description = 'Delete a report generated by package';

    protected $type = 'Remove Report';

    public function handle()
    {
        $name = $this->argument('name');
        $firstword = Str::title(str_replace('-',' ',$name));
        $studly = Str::studly($name);
        $camel = Str::camel($name);

        $this->info('Remove Report ' . $firstword);

        (new Filesystem())->delete(database_path("seeders/$studly"."Seeder.php"));
        (new Filesystem())->deleteDirectory(app_path("Http/Livewire/Backend/Report/$studly"));
        (new Filesystem())->delete(app_path("Http/Controllers/Backend/Report/$studly"."Controller.php"));
        (new Filesystem())->deleteDirectory(resource_path("views/backend/report/$name"));

        $this->comment('Please remove manually:');
        $this->comment('1. Web Route');

        $this->info('Remove Report ' . $name . ' done!');
    }

    protected function getStub()
    {
        return '';
    }
}
